### PR TITLE
improve error serialization compat

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]

**Comment by voxpelli** [comment]
This will make it diverge from my upstream `pony-cause` module and would in that case cause problems with typing I believe.

Should we/I upstream this into `pony-cause`?

**Comment by ronag** [comment]
Sorry to bother. I need this for a  deploy this week. Any chance for merge and release?

**Pull request merged**
